name: "Kiuwan"

on:
  push:
    branches: [master]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [master]
  schedule:
    - cron: '0 6 * * 4'

steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Kiuwan Baseline Analysis
        uses: lsacera/KiuwanBaselineAction@v1.0
        with:
          # Name of Kiuwan project
          project: ASVS App
          # Label for the analysis
          label: version
          # Username for kiuwan platform
          userid: ${{ secrets.KIUWAN_USER }}
          # Password for kiuwan platform
          password: ${{ secrets.KIUWAN_PASS }}
