name: Testing Kiuwan

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Kiuwan Delivery Action
      uses: lsacera/KiuwanActions@v0.4
      id: kstep
      with:
        project: ASVS
        label: ${{ github.run_number }}
        userid: ${{ secrets.KIUWAN_USER }}
        password: ${{ secrets.KIUWAN_PASS }}
      
    - name: show results step
      run: echo 'Ooh baby, guess the results were ${{ steps.kstep.outputs.result }} and the message was ${{ steps.kstep.outputs.message }} and the vulns are ${{ steps.kstep.outputs.auditresult }} and if you wanted to see them, head to ${{ steps.kstep.outputs.analysisurl }}.'
      

      
